version: '3.3'

services:
  web:
    build: .docker/apache
    volumes:
      - ./:/var/www/html
      - ./.docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/cache:/cache
    ports:
      - '80:80'
    environment:
      MYSQL_HOST: database
      MYSQL_USER: nette-sandbox
      MYSQL_DATABASE: nette-sandbox
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      PHP_IDE_CONFIG: serverName=localhost
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: mariadb:11.2
    volumes:
      - ./.docker/database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nette-sandbox
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: nette-sandbox

  adminer:
    image: adminer:4.8.1
    ports:
      - '8081:8080'
    environment:
      ADMINER_DEFAULT_SERVER: database

  composer:
    image: composer:latest
    volumes:
      - ./:/app
      - ./.docker/cache:/cache
    working_dir: /app
    command: composer install --ignore-platform-reqs
    environment:
      MYSQL_HOST: database
      MYSQL_USER: nette-sandbox
      MYSQL_DATABASE: nette-sandbox
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  console:
    image: webnazakazku/docker-php-build:8.2
    entrypoint: /tmp/entrypoint.sh
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/cache:/cache
      - ./.docker/php/xdebug.ini:/etc/php/8.2/mods-available/xdebug.ini
      - ./.docker/console/root:/root
      - ./.docker/console/.bashrc:/tmp/.bashrc
      - ./.docker/console/entrypoint.sh:/tmp/entrypoint.sh
    environment:
      PHP_IDE_CONFIG: serverName=localhost
      MYSQL_HOST: database
      MYSQL_USER: nette-sandbox
      MYSQL_DATABASE: nette-sandbox
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    extra_hosts:
      - host.docker.internal:host-gateway
